#Clonamos la aplicación
FROM node:10-alpine as build-step

RUN mkdir -p /app

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

RUN npm run build

FROM nginx:1.17.1-alpine

#Ponemos el nuevo servidor y le añadimos la aplicación
COPY --from=build-step /app/dist /usr/share/nginx/html

RUN chmod 755 -R /usr/share/nginx/html/
